- hosts: ceph-cluster
  gather_facts: no
  tasks:
    - include: facts.yml
    - name: gathering facts
      setup:
#    - name: debug toto
#      debug: var=hostvars[item]['ansible_local']['ssh_key_pub'].get("ssh_key_pub")
#      with_items: groups['ceph-cluster']
  roles:
    - common
    - ceph
