- name: add ceph repo
  apt_repository: repo='deb http://ceph.com/debian-firefly/ wheezy main' mode=644 state=present
- name: add gpg public key for ceph repo
  apt_key: url=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc state=present
