<<<<<<< HEAD
- name: ensure .ssh directory exists for root user
  file: dest=/root/.ssh owner=root group=root mode=0755 state=directory
- name: add zigzag repo
# useless password
  apt_repository: repo='deb http://zigzag:VpR+d52}qv@repo.zigzag.sx wheezy main' mode=644 state=present
- name: add gpg public key for zigzag repo
# useless password
  apt_key: url=http://zigzag:VpR+d52}qv@repo.zigzag.sx/key/zigzag.pub state=present
- name: refresh apt cache
  apt: update_cache=yes
- name: install base packages
  apt: pkg={{item}} state=present
  with_items:
   - git
   - git-core
   - curl
   - strace
   - htop
   - tcpdump
   - netcat
   - screen
   - htop
   - lsof
   - vim
   - ncdu
   - rsync
   - ntp
   - zigzag-base-config
- name: be sure ntpd is running and enabled
  service: name=ntp state=running enabled=yes
=======
---
# Common task for all nodes

- include: ssh_keys.yml
- include: repo.yml
- include: packages.yml
- include: ntp.yml
>>>>>>> 76c471a92a3265533ea35ebe00cd10f847179e71
