---
- name: check if ssh keys are present for root
  stat: path=/root/.ssh/id_rsa.pub
  register: p
#TODO: if /root/.ssh/id_rsa exists but is a directory, we will have a problem..
#TODO: maybe we could put the path in a variable
- name: create ssh keys if necessary
  command: "ssh-keygen -t rsa -b 2048 -q -f /root/.ssh/id_rsa -N ''"
  when: p.stat.exists == false
